services:
  
  web:
    build: .
    depends_on:
      - db
    ports:
      - "8016:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./odoo.conf:/etc/odoo/odoo.conf
      - ./extra-addons:/mnt/extra-addons
    networks:
      - private
   

  db:
    image: postgres:14.0
 
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    networks:
      - private

volumes:
  odoo-web-data:
  odoo-db-data:

networks:
  private:
    driver: bridge
    ipam:
      config:
        - subnet: "10.0.0.0/19"
          gateway: "10.0.0.1"

